AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template

  
Resources:
  InventoryManagementCF: #An inline comment
    Type: AWS::CodeCommit::Repository
    Properties:
    #  KmsKeyId: String
      RepositoryDescription: 'repository for backend apis to be deployed on lambda'
      RepositoryName: 'inventory-management-infra'
      Tags: 
        - Key: Env
          Value: global
        - Key: Project
          Value: inventory-management
  InventoryManagementCFPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore: 
        Type: S3
        Location: !Ref ArtifactBucket
      PipelineType: V2        

      Stages: 
        - Name: Source
          Actions: 
            - Name: AppSource
              InputArtifacts: []
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: '1'
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                BranchName: "deploy"
                RepositoryName: !GetAtt InventoryManagementCF.Name
                # RepositoryName: "inventory-management-infra"

        - Name: DeployCF
          Actions: 
            - Name: CFDeploy
              InputArtifacts:   
                - Name: SourceOutput
              ActionTypeId: 
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: "REPLACE_ON_FAILURE"
                Capabilities: "CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND"
                StackName: "deploy-inventorymanagement-infra"
                # RoleArn: "arn:aws:iam::339713106964:role/inventory-management-cf-role"
                RoleArn: !GetAtt CFRole.Arn
                TemplatePath: "SourceOutput::infra.yaml"
              OutputArtifacts: []

  CodePipelineRole:
    Type: AWS::IAM::Role     
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "codepipeline.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Description: 'codepipeline service role for accessing codecommit and CF'
      RoleName: inventory-management-cp-role 
  CodePipelineRolePolicy:
    Type: AWS::IAM::RolePolicy 
    Properties: 
      PolicyName: "inventory-management-cp-svc-role-pol"
      RoleName: !Ref CodePipelineRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - "codecommit:GetBranch"
              - "codecommit:GetCommit"
              - "codecommit:UploadArchive"
              - "codecommit:GetUploadArchiveStatus"
              - "codecommit:CancelUploadArchive"
            Resource: !GetAtt InventoryManagementCF.Arn
          - Effect: "Allow"
            Action:
              - "cloudformation:CreateStack"
              - "cloudformation:DeleteStack"
              - "cloudformation:DescribeStackEvents"
              - "cloudformation:DescribeStacks"
              - "cloudformation:UpdateStack"
              - "cloudformation:CreateChangeSet"
              - "cloudformation:DeleteChangeSet"
              - "cloudformation:DescribeChangeSet"
              - "cloudformation:ExecuteChangeSet"
              - "cloudformation:SetStackPolicy"
              - "cloudformation:ValidateTemplate"
              - "iam:PassRole"
            Resource: "*" 
          - Effect: "Allow"
            Action: "s3:*"
            Resource:
              - !GetAtt ArtifactBucket.Arn
              - !Join ["",[!GetAtt ArtifactBucket.Arn,"/*"]]
        

  CFRole:
    Type: AWS::IAM::Role     
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "cloudformation.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Description: 'codepipeline service role for accessing codecommit and CF'
      RoleName: inventory-management-cf-role 
  CFRolePolicy:
    Type: AWS::IAM::RolePolicy 
    Properties: 
      PolicyName: "inventory-management-cp-svc-role-pol"
      RoleName: !Ref CFRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - "*"
            Resource: "*"
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: inventory-management-bizz-solutions-infra-bucket-7677
